<?php

declare(strict_types=1);
?>
<section class="container statistics-page">
    <div class="statistics-page__hero">
        <div class="statistics-page__copy">
            <span class="eyebrow">Public statistics</span>
            <h1>Platform activity overview</h1>
            <p class="lead">
                These indicators stay aggregated and anonymized. They help users understand catalog activity without exposing individual student or recruiter data.
            </p>
        </div>

        <aside class="statistics-page__hero-card">
            <span class="eyebrow">Data scope</span>
            <h2>Readable, shared, and safe</h2>
            <p class="meta">
                This page focuses on public platform signals: published offers, company presence, application volume, and the main distribution patterns behind the internship workflow.
            </p>
        </aside>
    </div>
</section>

<section class="container statistics-page__content">
    <div class="statistics-page__main">
        <section class="statistics-metrics">
            <article class="statistics-metric-card">
                <span class="eyebrow">Published offers</span>
                <strong><?= e((string) $publishedOfferCount) ?></strong>
                <p class="meta">Internship opportunities currently visible in the public catalog.</p>
            </article>

            <article class="statistics-metric-card">
                <span class="eyebrow">Companies</span>
                <strong><?= e((string) $companyCount) ?></strong>
                <p class="meta">Company profiles available across the platform directory.</p>
            </article>

            <article class="statistics-metric-card">
                <span class="eyebrow">Applications</span>
                <strong><?= e((string) $applicationCount) ?></strong>
                <p class="meta">Applications submitted through the internship workflow.</p>
            </article>

            <article class="statistics-metric-card">
                <span class="eyebrow">Average per offer</span>
                <strong><?= e(number_format((float) $averageApplicationsPerOffer, 1, ',', ' ')) ?></strong>
                <p class="meta">Average applications generated by each published offer.</p>
            </article>
        </section>

        <section class="statistics-section">
            <div class="section-heading section-heading--compact">
                <div>
                    <span class="eyebrow">Catalog signals</span>
                    <h2>Operational distributions</h2>
                </div>
            </div>

            <div class="statistics-grid">
                <article class="statistics-card">
                    <h3>Offers by location</h3>
                    <?php if ($topLocations === []): ?>
                        <p class="meta">No published offers are available yet.</p>
                    <?php else: ?>
                        <ul class="statistics-list">
                            <?php foreach ($topLocations as $location): ?>
                                <li>
                                    <span><?= e((string) $location['label']) ?></span>
                                    <strong><?= e((string) $location['total']) ?></strong>
                                </li>
                            <?php endforeach; ?>
                        </ul>
                    <?php endif; ?>
                </article>

                <article class="statistics-card">
                    <h3>Offers by contract type</h3>
                    <?php if ($topContractTypes === []): ?>
                        <p class="meta">No contract types are available yet.</p>
                    <?php else: ?>
                        <ul class="statistics-list">
                            <?php foreach ($topContractTypes as $contractType): ?>
                                <li>
                                    <span><?= e((string) $contractType['label']) ?></span>
                                    <strong><?= e((string) $contractType['total']) ?></strong>
                                </li>
                            <?php endforeach; ?>
                        </ul>
                    <?php endif; ?>
                </article>
            </div>
        </section>

        <section class="statistics-section">
            <div class="section-heading section-heading--compact">
                <div>
                    <span class="eyebrow">Application flow</span>
                    <h2>Application status distribution</h2>
                </div>
            </div>

            <article class="statistics-card">
                <?php if ($applicationStatuses === []): ?>
                    <p class="meta">No applications have been recorded yet.</p>
                <?php else: ?>
                    <ul class="statistics-list">
                        <?php foreach ($applicationStatuses as $status): ?>
                            <li>
                                <span><?= e(ucfirst((string) $status['label'])) ?></span>
                                <strong><?= e((string) $status['total']) ?></strong>
                            </li>
                        <?php endforeach; ?>
                    </ul>
                <?php endif; ?>
            </article>
        </section>
    </div>

    <aside class="statistics-page__aside">
        <div class="statistics-card statistics-card--soft">
            <span class="eyebrow">What this page means</span>
            <h2>Use the figures as platform indicators.</h2>
            <p class="meta">
                These metrics help compare catalog density, company presence, and application flow over time. They are designed to stay understandable without exposing personal records.
            </p>

            <div class="statistics-card__stack">
                <a class="button button--primary" href="<?= e(url('/offres')) ?>">Explore internships</a>
                <a class="button button--ghost" href="<?= e(url('/entreprises')) ?>">Browse companies</a>
                <a class="button button--ghost" href="<?= e(url('/login')) ?>">Sign in</a>
            </div>
        </div>
    </aside>
</section>
